<?php 
$EncryptedSek = "PKHUKtGgAEalozjlI40dAoJ85+eleJL16fIH8oP6gLzmFTg9sgltEsL4SdULRi1V";                  // Sek that we get from Authentication Api Response


$AppKey = "ZEtrRXA3UWRZalZqT2xtZ3IwOElFa0ZXNnRIazdUSGQ=";                        // Generated by User for Authentication Request Payload

$options = 0;

$encryption = $EncryptedSek;      // Sample Encrypted Sek  aX/vpj/5zH4+73h92sATT8YuKvR+fieLgGKYId5mCyLlCZqCyF1TFO3b86rJ7WI6

$ciphering = "AES-256-ECB";

$decryption_key =  base64_decode($AppKey);

$decryption_iv = '';
 
 
$decryption=openssl_decrypt ($encryption, $ciphering,$decryption_key, $options, $decryption_iv);
 
$base64encodeddecryptedsek = base64_encode($decryption);
echo "Decrypted Sek (Base64 Encoded): " . $base64encodeddecryptedsek;
?>