<?php

/**
 * Developer-defined app settings metadata.
 * DB tables:
 *   app_settings       — setting_key, setting_value
 *   settings_audit_log — change history
 *
 * To add a setting:
 * 1. Add an entry here (label, input, type, sort, etc.)
 * 2. INSERT the row into app_settings (setting_key, setting_value)
 */
return [
    'invoice_prefix' => [
        'label' => 'Invoice prefix',
        'group' => 'invoice',
        'description' => 'Prefix prepended to auto-generated invoice numbers.',
        'input' => 'text',
        'type' => 'string',
        'default' => 'INV',
        'editable' => true,
        'active' => true,
        'sort' => 10,
    ],
    'invoice_series' => [
        'label' => 'Invoice series',
        'group' => 'invoice',
        'description' => 'Next running number used for invoice generation. Updated automatically when invoices are created.',
        'input' => 'number',
        'type' => 'int',
        'default' => 1,
        'editable' => true,
        'active' => true,
        'sort' => 20,
    ],
    'terms_and_conditions' => [
        'label' => 'Terms and conditions',
        'group' => 'invoice',
        'description' => 'Default terms printed on invoices.',
        'input' => 'textarea',
        'type' => 'text',
        'default' => '',
        'editable' => true,
        'active' => true,
        'sort' => 30,
    ],
    'high_value_transaction_limit' => [
        'label' => 'High value transaction limit',
        'group' => 'compliance',
        'description' => 'Threshold for Section 269ST / Rule 114B POS compliance prompts. Default: ₹2,00,000.',
        'input' => 'number',
        'type' => 'decimal',
        'default' => 200000.00,
        'editable' => true,
        'active' => true,
        'sort' => 10,
    ],
    'firm_name' => [
        'label' => 'Firm name',
        'group' => 'company',
        'description' => 'Legal name shown on invoices and shipping documents.',
        'input' => 'text',
        'type' => 'string',
        'default' => '',
        'editable' => true,
        'active' => true,
        'sort' => 10,
    ],
    'firm_pan' => [
        'label' => 'PAN',
        'group' => 'company',
        'description' => 'Permanent Account Number.',
        'input' => 'text',
        'type' => 'string',
        'default' => '',
        'editable' => true,
        'active' => true,
        'sort' => 20,
    ],
    'firm_gst' => [
        'label' => 'GSTIN',
        'group' => 'company',
        'description' => 'GST identification number.',
        'input' => 'text',
        'type' => 'string',
        'default' => '',
        'editable' => true,
        'active' => true,
        'sort' => 30,
    ],
    'firm_address' => [
        'label' => 'Address',
        'group' => 'company',
        'description' => 'Registered business address.',
        'input' => 'textarea',
        'type' => 'text',
        'default' => '',
        'editable' => true,
        'active' => true,
        'sort' => 40,
    ],
    'firm_phone' => [
        'label' => 'Phone',
        'group' => 'company',
        'description' => 'Primary contact phone number.',
        'input' => 'text',
        'type' => 'string',
        'default' => '',
        'editable' => true,
        'active' => true,
        'sort' => 50,
    ],
    'firm_city' => [
        'label' => 'City',
        'group' => 'company',
        'input' => 'text',
        'type' => 'string',
        'default' => '',
        'editable' => true,
        'active' => true,
        'sort' => 60,
    ],
    'firm_state' => [
        'label' => 'State',
        'group' => 'company',
        'input' => 'text',
        'type' => 'string',
        'default' => '',
        'editable' => true,
        'active' => true,
        'sort' => 70,
    ],
    'firm_country' => [
        'label' => 'Country',
        'group' => 'company',
        'input' => 'text',
        'type' => 'string',
        'default' => '',
        'editable' => true,
        'active' => true,
        'sort' => 80,
    ],
    'firm_pin' => [
        'label' => 'PIN code',
        'group' => 'company',
        'description' => 'Postal / ZIP code used as dispatch fallback.',
        'input' => 'text',
        'type' => 'string',
        'default' => '',
        'editable' => true,
        'active' => true,
        'sort' => 90,
    ],
    'firm_state_code' => [
        'label' => 'State code',
        'group' => 'company',
        'description' => 'Numeric state code for tax / e-invoice integrations.',
        'input' => 'number',
        'type' => 'int',
        'default' => null,
        'editable' => true,
        'active' => true,
        'sort' => 100,
    ],
    'firm_email' => [
        'label' => 'Email',
        'group' => 'company',
        'description' => 'Company email for documents and notifications.',
        'input' => 'text',
        'type' => 'string',
        'default' => '',
        'editable' => true,
        'active' => true,
        'sort' => 110,
    ],
];
