<?php

/**
 * Developer-defined app settings metadata.
 * DB tables:
 *   app_settings       — setting_key, setting_value
 *   settings_audit_log — change history
 *
 * To add a setting:
 * 1. Add an entry here (label, input, type, sort, etc.)
 * 2. INSERT the row into app_settings (setting_key, setting_value)
 */
return [
    'firm_name' => [
        'label' => 'Firm name',
        'description' => 'Legal name of the company as printed on invoices and documents.',
        'input' => 'text',
        'type' => 'string',
        'default' => 'EXOTIC INDIA ART PVT LTD',
        'editable' => true,
        'active' => true,
        'sort' => 1,
    ],
    'gstin' => [
        'label' => 'GSTIN',
        'description' => 'Company GST identification number (15 characters).',
        'input' => 'text',
        'type' => 'string',
        'default' => '07AADCE1400C1ZJ',
        'editable' => true,
        'active' => true,
        'sort' => 2,
    ],
    'firm_pan' => [
        'label' => 'Firm PAN',
        'description' => 'Company Permanent Account Number (PAN).',
        'input' => 'text',
        'type' => 'string',
        'default' => 'AADCE1400C',
        'editable' => true,
        'active' => true,
        'sort' => 3,
    ],
    'firm_address' => [
        'label' => 'Firm address',
        'description' => 'Registered street address of the firm for invoices, customs & shipping documents.',
        'input' => 'textarea',
        'type' => 'string',
        'default' => '101, Plaza A-1, Paschim Vihar',
        'editable' => true,
        'active' => true,
        'sort' => 4,
    ],
    'firm_city' => [
        'label' => 'Firm city',
        'description' => 'City of the firm (e.g. New Delhi).',
        'input' => 'text',
        'type' => 'string',
        'default' => 'New Delhi',
        'editable' => true,
        'active' => true,
        'sort' => 5,
    ],
    'firm_pin' => [
        'label' => 'Firm pincode / zip',
        'description' => 'Postal / pincode of the firm.',
        'input' => 'text',
        'type' => 'string',
        'default' => '110063',
        'editable' => true,
        'active' => true,
        'sort' => 6,
    ],
    'firm_country' => [
        'label' => 'Firm country',
        'description' => 'Country of the firm (e.g. India).',
        'input' => 'text',
        'type' => 'string',
        'default' => 'India',
        'editable' => true,
        'active' => true,
        'sort' => 7,
    ],
    'firm_iec' => [
        'label' => 'Firm IEC code',
        'description' => 'Import Export Code (IEC) issued by DGFT.',
        'input' => 'text',
        'type' => 'string',
        'default' => '0505012345',
        'editable' => true,
        'active' => true,
        'sort' => 8,
    ],
    'authorized_signatory' => [
        'label' => 'Authorized signatory',
        'description' => 'Authorized signatory title/name for export declarations and documents.',
        'input' => 'text',
        'type' => 'string',
        'default' => 'Authorized Signatory',
        'editable' => true,
        'active' => true,
        'sort' => 9,
    ],
    'stock_replenishment_months' => [
        'label' => 'Stock replenishment lookback (months)',
        'description' => 'Number of months of sales history used to calculate average demand and recommended stock levels.',
        'input' => 'number',
        'type' => 'int',
        'default' => 1,
        'editable' => true,
        'active' => true,
        'sort' => 10,
    ],
    'stock_replenishment_book_price_cutoff' => [
        'label' => 'Book price cutoff for replenishment',
        'description' => 'Minimum book selling price (₹) included in stock replenishment calculations. Books below this price are excluded. Use 0 for no cutoff.',
        'input' => 'number',
        'type' => 'int',
        'default' => 0,
        'editable' => true,
        'active' => true,
        'sort' => 20,
    ],
    'invoice_prefix' => [
        'label' => 'Invoice number prefix',
        'description' => 'Prefix for auto-generated invoice numbers (e.g. inv/2025-26/ or INV).',
        'input' => 'text',
        'type' => 'string',
        'default' => 'INV',
        'editable' => true,
        'active' => true,
        'sort' => 100,
    ],
    'invoice_series' => [
        'label' => 'Invoice series counter',
        'description' => 'Last used invoice series number; incremented automatically when a new invoice is created.',
        'input' => 'number',
        'type' => 'int',
        'default' => 0,
        'editable' => true,
        'active' => true,
        'sort' => 110,
    ],
    'terms_and_conditions' => [
        'label' => 'Invoice terms and conditions',
        'description' => 'Default terms printed on invoices.',
        'input' => 'textarea',
        'type' => 'string',
        'default' => '',
        'editable' => true,
        'active' => true,
        'sort' => 120,
    ],
    'high_value_transaction_limit' => [
        'label' => 'High value transaction limit (₹)',
        'description' => 'Orders above this amount may require additional approval.',
        'input' => 'number',
        'type' => 'decimal',
        'default' => 200000.00,
        'editable' => true,
        'active' => true,
        'sort' => 130,
    ],
];
