<?php

/**
 * Partner credential JSON templates and field hints for courier account UI.
 *
 * Stored in courier_partner_accounts.credentials_json as a single object per account.
 */
return [
    'aramex' => [
        'label' => 'Aramex',
        'description' => 'International export (ProductGroup EXP). Official Aramex TEST account: 60531487 (entity BOM) — see docs/ARAMEX_SANDBOX_SETUP.md. Production: separate rows for 60524328 and 60525897 (entity DEL). Label ReportID 9729.',
        'template' => [
            'username' => '',
            'password' => '',
            'account_number' => '',
            'account_pin' => '',
            'account_entity' => 'DEL',
            'account_country_code' => 'IN',
            'version' => 'v1.0',
            'client_source' => 24,
            'label_info' => [
                'report_id' => 9729,
                'report_type' => 'URL',
            ],
            'shipper_gstin' => '07AADCE1400C1ZJ',
            'exporter_type' => 'UT',
            'sandbox_api_base_url' => 'https://ws.aramex.net/ShippingAPI.V2',
            'sandbox_shipping_wsdl' => 'https://ws.aramex.net/ShippingAPI.V2/Shipping/Service_1_0.svc?wsdl',
            'sandbox_tracking_wsdl' => 'https://ws.aramex.net/ShippingAPI.V2/Tracking/Service_1_0.svc?wsdl',
            'production_api_base_url' => 'https://ws.aramex.net/ShippingAPI.V2',
            'production_shipping_wsdl' => 'https://ws.aramex.net/ShippingAPI.V2/Shipping/Service_1_0.svc?wsdl',
            'production_tracking_wsdl' => 'https://ws.aramex.net/ShippingAPI.V2/Tracking/Service_1_0.svc?wsdl',
            'rating_currency' => 'USD',
            'default_product_group' => 'EXP',
            'default_product_type' => '',
            'shipper' => [
                'company_name' => 'Exotic India Art Pvt Ltd',
                'full_name' => 'Ritvik',
                'phone' => '9810028401',
                'email' => 'rithvik@exoticindia.com',
                'line1' => 'A-16/1, Wazirpur Industrial Area',
                'line2' => '',
                'city' => 'Delhi',
                'postcode' => '110052',
                'state' => '',
                'country_code' => 'IN',
            ],
        ],
        'secret_keys' => ['password', 'account_pin'],
    ],
    'bluedart' => [
        'label' => 'Blue Dart',
        'description' => 'Domestic express. Implement API in BlueDartAdapter. Credentials stored as JSON; use environment dropdown for sandbox vs production.',
        'template' => [
            'login_id' => '',
            'licence_key' => '',
            'customer_code' => '',
            'origin_area' => '',
            'customer_pincode' => '110052',
            'registered_name' => 'Exotic India Art Pvt Ltd',
            'rating_currency' => 'INR',
            'default_product_code' => '',
            'sandbox_api_base_url' => 'https://api.bluedart.com/servlet/RoutingServlet',
            'production_api_base_url' => 'https://api.bluedart.com/servlet/RoutingServlet',
            'shipper' => [
                'company_name' => 'Exotic India Art Pvt Ltd',
                'full_name' => '',
                'phone' => '',
                'email' => '',
                'line1' => 'A-16/1, Wazirpur Industrial Area',
                'city' => 'Delhi',
                'postcode' => '110052',
                'state' => 'Delhi',
                'country_code' => 'IN',
            ],
        ],
        'secret_keys' => ['licence_key'],
    ],
    'delhivery' => [
        'label' => 'Delhivery',
        'description' => 'Delhivery One APIs. Order create requires pickup_location_name = exact facility name from Delhivery One → Settings → Pickup Locations (case-sensitive). Shiprocket pickup names are NOT valid for Delhivery.',
        'template' => [
            'client_name' => 'Exotic India Art Pvt Ltd',
            'api_token' => '5327198a87ee782d219fead3b9040b5da8d94671',
            'pickup_location_name' => 'Exotic India',
            'pickup_location_aliases' => [
                'Head Office' => 'Exotic India',
            ],
            'rate_api_path' => '',
            'order_create_api_path' => '',
            'packing_slip_api_path' => '',
            'seller_gst_tin' => '',
            'registered_name' => 'Exotic India Art Pvt Ltd',
            'sandbox_api_base_url' => 'https://staging-express.delhivery.com',
            'production_api_base_url' => 'https://track.delhivery.com',
            'shipper' => [
                'company_name' => 'Exotic India Art Pvt Ltd',
                'full_name' => 'Vipin Goel',
                'phone' => '',
                'email' => '',
                'line1' => 'A-16/1, Wazirpur Industrial Area',
                'city' => 'Delhi',
                'postcode' => '110052',
                'state' => 'Delhi',
                'country_code' => 'IN',
            ],
        ],
        'secret_keys' => ['api_token'],
    ],
    'dhl' => [
        'label' => 'DHL Express',
        'description' => 'MyDHL API (REST). Sandbox and production use different base URLs.',
        'template' => [
            'account_number' => '',
            'api_key' => '',
            'api_secret' => '',
            'rating_currency' => 'INR',
            'default_global_product_code' => '',
            'default_local_product_code' => '',
            'sandbox_api_base_url' => 'https://express.api.dhl.com/mydhlapi/test',
            'production_api_base_url' => 'https://express.api.dhl.com/mydhlapi',
            'shipper' => [
                'company_name' => 'Exotic India Art Pvt Ltd',
                'full_name' => '',
                'phone' => '',
                'email' => '',
                'line1' => '',
                'line2' => '',
                'city' => 'Delhi',
                'postcode' => '110052',
                'state' => '',
                'country_code' => 'IN',
            ],
        ],
        'secret_keys' => ['api_secret'],
    ],
    'fedex' => [
        'label' => 'FedEx',
        'description' => 'International express. FedEx REST API (OAuth). Implement in FedExAdapter.',
        'template' => [
            'client_id' => '',
            'client_secret' => '',
            'account_number' => '',
            'rating_currency' => 'USD',
            'default_service_type' => '',
            'sandbox_api_base_url' => 'https://apis-sandbox.fedex.com',
            'production_api_base_url' => 'https://apis.fedex.com',
            'shipper' => [
                'company_name' => 'Exotic India Art Pvt Ltd',
                'full_name' => '',
                'phone' => '',
                'email' => '',
                'line1' => 'A-16/1, Wazirpur Industrial Area',
                'line2' => '',
                'city' => 'Delhi',
                'postcode' => '110052',
                'state' => '',
                'country_code' => 'IN',
            ],
        ],
        'secret_keys' => ['client_secret'],
    ],
    'ups' => [
        'label' => 'UPS',
        'description' => 'International express. UPS REST API (OAuth). Implement in UPSAdapter.',
        'template' => [
            'client_id' => '',
            'client_secret' => '',
            'account_number' => '',
            'rating_currency' => 'USD',
            'default_service_code' => '',
            'sandbox_api_base_url' => 'https://wwwcie.ups.com',
            'production_api_base_url' => 'https://onlinetools.ups.com',
            'shipper' => [
                'company_name' => 'Exotic India Art Pvt Ltd',
                'full_name' => '',
                'phone' => '',
                'email' => '',
                'line1' => 'A-16/1, Wazirpur Industrial Area',
                'line2' => '',
                'city' => 'Delhi',
                'postcode' => '110052',
                'state' => '',
                'country_code' => 'IN',
            ],
        ],
        'secret_keys' => ['client_secret'],
    ],
    'shiprocket' => [
        'label' => 'Shiprocket',
        'description' => 'Domestic aggregator credentials. Set sandbox and production API base URLs.',
        'template' => [
            'email' => '',
            'password' => '',
            'token' => '',
            'pickup_location' => '',
            'sandbox_api_base_url' => 'https://apiv2.shiprocket.in',
            'production_api_base_url' => 'https://apiv2.shiprocket.in',
        ],
        'secret_keys' => ['password', 'token'],
    ],
    '_default' => [
        'label' => 'Generic partner',
        'description' => 'Free-form JSON object. Include sandbox_url and production_url (or sandbox_api_base_url / production_api_base_url).',
        'template' => [
            'sandbox_api_base_url' => '',
            'production_api_base_url' => '',
            'api_key' => '',
            'api_secret' => '',
        ],
        'secret_keys' => ['api_secret', 'password', 'token'],
    ],
];
