<?php

/**
 * Partner credential schemas for Courier accounts.
 *
 * - fields: empty skeleton for UI "Load partner template" (used by admin UI only)
 * - reference: copy-paste values for developers — NOT read at runtime; DB is the source of truth
 *
 * Runtime adapters load credentials only from courier_partner_accounts.credentials_json.
 */
return [
    'aramex' => [
        'label' => 'Aramex',
        'description' => 'International export (ProductGroup EXP). See docs/ARAMEX_SANDBOX_SETUP.md for sandbox account setup.',
        'fields' => [
            'username' => '',
            'password' => '',
            'account_number' => '',
            'account_pin' => '',
            'account_entity' => '',
            'account_country_code' => '',
            'version' => '',
            'client_source' => '',
            'label_info' => [
                'report_id' => '',
                'report_type' => '',
            ],
            'shipper_gstin' => '',
            'exporter_type' => '',
            'sandbox_api_base_url' => '',
            'sandbox_shipping_wsdl' => '',
            'sandbox_tracking_wsdl' => '',
            'production_api_base_url' => '',
            'production_shipping_wsdl' => '',
            'production_tracking_wsdl' => '',
            'rating_currency' => '',
            'default_product_group' => '',
            'default_product_type' => '',
            'shipper' => [
                'company_name' => '',
                'full_name' => '',
                'phone' => '',
                'email' => '',
                'line1' => '',
                'line2' => '',
                'city' => '',
                'postcode' => '',
                'state' => '',
                'country_code' => '',
            ],
        ],
        'reference' => [
            'account_entity' => 'DEL',
            'account_country_code' => 'IN',
            'version' => 'v1.0',
            'client_source' => 24,
            'label_info' => [
                'report_id' => 9729,
                'report_type' => 'URL',
            ],
            'shipper_gstin' => '07AADCE1400C1ZJ',
            'exporter_type' => 'UT',
            'sandbox_api_base_url' => 'https://ws.aramex.net/ShippingAPI.V2',
            'sandbox_shipping_wsdl' => 'https://ws.aramex.net/ShippingAPI.V2/Shipping/Service_1_0.svc?wsdl',
            'sandbox_tracking_wsdl' => 'https://ws.aramex.net/ShippingAPI.V2/Tracking/Service_1_0.svc?wsdl',
            'production_api_base_url' => 'https://ws.aramex.net/ShippingAPI.V2',
            'production_shipping_wsdl' => 'https://ws.aramex.net/ShippingAPI.V2/Shipping/Service_1_0.svc?wsdl',
            'production_tracking_wsdl' => 'https://ws.aramex.net/ShippingAPI.V2/Tracking/Service_1_0.svc?wsdl',
            'rating_currency' => 'USD',
            'default_product_group' => 'EXP',
            'shipper' => [
                'company_name' => 'Exotic India Art Pvt Ltd',
                'full_name' => 'Ritvik',
                'phone' => '9810028401',
                'email' => 'rithvik@exoticindia.com',
                'line1' => 'A-16/1, Wazirpur Industrial Area',
                'line2' => '',
                'city' => 'Delhi',
                'postcode' => '110052',
                'state' => '',
                'country_code' => 'IN',
            ],
        ],
        'secret_keys' => ['password', 'account_pin'],
    ],
    'bluedart' => [
        'label' => 'Blue Dart',
        'production_only' => true,
        'description' => 'Blue Dart (DHL eCommerce India REST APIs). Production only. JWT auth tries: explicit consumer_key/secret (DHL portal), then login_id+licence_key, then customer_code+licence_key. Profile uses login_id+licence_key on every call. Waybill also needs customer_code, origin_area, shipper.',
        'fields' => [
            'login_id' => '',
            'licence_key' => '',
            'shipment_licence_key' => '',
            'waybill_api_path' => '',
            'register_pickup_on_waybill' => '',
            'tracking_licence_key' => '',
            'licence_key' => '',
            'customer_code' => '',
            'cod_customer_code' => '',
            'origin_area' => '',
            'customer_pincode' => '',
            'registered_name' => '',
            'rating_currency' => '',
            'default_product_code' => '',
            'default_service_type' => '',
            'consumer_key' => '',
            'consumer_secret' => '',
            'jwt_token' => '',
            'dhl_client_id' => '',
            'dhl_client_secret' => '',
            'allowed_service_types' => [],
            'api_gateway_base_url' => '',
            'token_api_path' => '',
            'rate_per_kg_inr' => '',
            'rate_minimum_inr' => '',
            'rate_products' => [],
            'rate_estimate' => [
                'default_per_kg_inr' => '',
                'default_minimum_inr' => '',
                'products' => [],
            ],
            'production_api_base_url' => '',
            'shipper' => [
                'company_name' => '',
                'full_name' => '',
                'phone' => '',
                'email' => '',
                'line1' => '',
                'city' => '',
                'postcode' => '',
                'state' => '',
                'country_code' => '',
            ],
        ],
        'reference' => [
            'login_id' => 'DEL74014',
            'shipment_licence_key' => '',
            'tracking_licence_key' => 'hgtpjhk0ei0yp6oqpomstjuevjuokjls',
            'licence_key' => 'dqeqrroq0ote7iymnm7iomrtkwevkjon',
            'customer_code' => '851756',
            'origin_area' => 'DEL',
            'customer_pincode' => '110052',
            'registered_name' => 'EXOTIC INDIA ART PVT. LTD',
            'rating_currency' => 'INR',
            'default_service_type' => 'Surface',
            'api_gateway_base_url' => 'https://apigateway.bluedart.com',
            'consumer_key' => '(from DHL Developer Portal → your Blue Dart app)',
            'consumer_secret' => '(from DHL Developer Portal — keep secret)',
            'production_api_base_url' => 'https://api.bluedart.com/servlet/RoutingServlet',
            'shipper' => [
                'company_name' => 'EXOTIC INDIA ART PVT. LTD',
                'full_name' => 'Ritvik',
                'phone' => '9821791175',
                'email' => 'rithvik@exoticindia.com',
                'line1' => 'A-16/1, Wazirpur Industrial Area',
                'city' => 'Delhi',
                'postcode' => '110052',
                'state' => 'Delhi',
                'country_code' => 'IN',
            ],
        ],
        'secret_keys' => ['shipment_licence_key', 'tracking_licence_key', 'licence_key', 'consumer_secret', 'jwt_token', 'dhl_client_secret'],
    ],
    'delhivery' => [
        'label' => 'Delhivery',
        'production_only' => true,
        'description' => 'Delhivery One APIs. Production only. pickup_location_name must match Delhivery One → Settings → Pickup Locations exactly. Use pickup_location_aliases to map Shiprocket pickup names.',
        'fields' => [
            'client_name' => '',
            'api_token' => '',
            'pickup_location_name' => '',
            'pickup_location_aliases' => [],
            'rate_api_path' => '',
            'order_create_api_path' => '',
            'packing_slip_api_path' => '',
            'label_pdf_size' => '',
            'seller_gst_tin' => '',
            'registered_name' => '',
            'production_api_base_url' => '',
            'shipper' => [
                'company_name' => '',
                'full_name' => '',
                'phone' => '',
                'email' => '',
                'line1' => '',
                'city' => '',
                'postcode' => '',
                'state' => '',
                'country_code' => '',
            ],
        ],
        'reference' => [
            'client_name' => 'Exotic India Art Pvt Ltd',
            'api_token' => '5327198a87ee782d219fead3b9040b5da8d94671',
            'pickup_location_name' => 'EXOTIC1 SURFACE',
            'pickup_location_aliases' => [
                'Head Off' => 'EXOTIC1 SURFACE',
                'Head Office' => 'EXOTIC1 SURFACE',
            ],
            'label_pdf_size' => '4R',
            'seller_gst_tin' => '07AADCE1400C1ZJ',
            'registered_name' => 'Exotic India Art Pvt Ltd',
            'production_api_base_url' => 'https://track.delhivery.com',
            'shipper' => [
                'company_name' => 'Exotic India Art Pvt Ltd',
                'full_name' => 'Vipin Goel',
                'phone' => '',
                'email' => '',
                'line1' => 'A-16/1, Wazirpur Industrial Area',
                'city' => 'Delhi',
                'postcode' => '110052',
                'state' => 'Delhi',
                'country_code' => 'IN',
            ],
        ],
        'secret_keys' => ['api_token'],
    ],
    'dhl' => [
        'label' => 'DHL Express',
        'description' => 'MyDHL API (REST). Sandbox and production use different base URLs.',
        'fields' => [
            'account_number' => '',
            'api_key' => '',
            'api_secret' => '',
            'rating_currency' => '',
            'default_global_product_code' => '',
            'default_local_product_code' => '',
            'sandbox_api_base_url' => '',
            'production_api_base_url' => '',
            'shipper' => [
                'company_name' => '',
                'full_name' => '',
                'phone' => '',
                'email' => '',
                'line1' => '',
                'line2' => '',
                'city' => '',
                'postcode' => '',
                'state' => '',
                'country_code' => '',
            ],
        ],
        'reference' => [
            'rating_currency' => 'INR',
            'sandbox_api_base_url' => 'https://express.api.dhl.com/mydhlapi/test',
            'production_api_base_url' => 'https://express.api.dhl.com/mydhlapi',
            'shipper' => [
                'company_name' => 'Exotic India Art Pvt Ltd',
                'city' => 'Delhi',
                'postcode' => '110052',
                'country_code' => 'IN',
            ],
        ],
        'secret_keys' => ['api_secret'],
    ],
    'fedex' => [
        'label' => 'FedEx',
        'description' => 'International express. FedEx REST API (OAuth).',
        'fields' => [
            'client_id' => '',
            'client_secret' => '',
            'account_number' => '',
            'rating_currency' => '',
            'default_service_type' => '',
            'sandbox_api_base_url' => '',
            'production_api_base_url' => '',
            'shipper' => [
                'company_name' => '',
                'full_name' => '',
                'phone' => '',
                'email' => '',
                'line1' => '',
                'line2' => '',
                'city' => '',
                'postcode' => '',
                'state' => '',
                'country_code' => '',
            ],
        ],
        'reference' => [
            'rating_currency' => 'USD',
            'sandbox_api_base_url' => 'https://apis-sandbox.fedex.com',
            'production_api_base_url' => 'https://apis.fedex.com',
            'shipper' => [
                'company_name' => 'Exotic India Art Pvt Ltd',
                'line1' => 'A-16/1, Wazirpur Industrial Area',
                'city' => 'Delhi',
                'postcode' => '110052',
                'country_code' => 'IN',
            ],
        ],
        'secret_keys' => ['client_secret'],
    ],
    'ups' => [
        'label' => 'UPS',
        'description' => 'International express. UPS REST API (OAuth).',
        'fields' => [
            'client_id' => '',
            'client_secret' => '',
            'account_number' => '',
            'rating_currency' => '',
            'default_service_code' => '',
            'sandbox_api_base_url' => '',
            'production_api_base_url' => '',
            'shipper' => [
                'company_name' => '',
                'full_name' => '',
                'phone' => '',
                'email' => '',
                'line1' => '',
                'line2' => '',
                'city' => '',
                'postcode' => '',
                'state' => '',
                'country_code' => '',
            ],
        ],
        'reference' => [
            'rating_currency' => 'USD',
            'sandbox_api_base_url' => 'https://wwwcie.ups.com',
            'production_api_base_url' => 'https://onlinetools.ups.com',
            'shipper' => [
                'company_name' => 'Exotic India Art Pvt Ltd',
                'line1' => 'A-16/1, Wazirpur Industrial Area',
                'city' => 'Delhi',
                'postcode' => '110052',
                'country_code' => 'IN',
            ],
        ],
        'secret_keys' => ['client_secret'],
    ],
    'shiprocket' => [
        'label' => 'Shiprocket',
        'description' => 'Domestic aggregator credentials.',
        'fields' => [
            'email' => '',
            'password' => '',
            'token' => '',
            'pickup_location' => '',
            'sandbox_api_base_url' => '',
            'production_api_base_url' => '',
        ],
        'reference' => [
            'pickup_location' => 'Head Off',
            'sandbox_api_base_url' => 'https://apiv2.shiprocket.in',
            'production_api_base_url' => 'https://apiv2.shiprocket.in',
            'environment' => 'production',
        ],
        'secret_keys' => ['password', 'token'],
    ],
    '_default' => [
        'label' => 'Generic partner',
        'description' => 'Free-form JSON. Include sandbox_api_base_url and production_api_base_url as needed.',
        'fields' => [
            'sandbox_api_base_url' => '',
            'production_api_base_url' => '',
            'api_key' => '',
            'api_secret' => '',
        ],
        'secret_keys' => ['api_secret', 'password', 'token'],
    ],
];
