<?php
/**
 * Common Dispatch Details Modal Partial
 * Included in views/posinvoice/index.php and views/dispatch/index.php
 */
global $commanModel;
$exoticAddresses = (isset($commanModel) && method_exists($commanModel, 'get_exotic_address')) 
    ? $commanModel->get_exotic_address() 
    : [];
?>
<div id="commonDispatchModal" class="fixed inset-0 z-[150] hidden items-center justify-center bg-black/50 p-4 backdrop-blur-sm overflow-y-auto">
    <div class="relative w-full max-w-2xl mx-auto my-auto rounded-2xl bg-white shadow-2xl border border-gray-100 overflow-hidden text-gray-800 animate-in fade-in zoom-in duration-200">
        
        <!-- Modal Header -->
        <div class="flex items-center justify-between bg-gradient-to-r from-orange-50 via-orange-100/50 to-white px-6 py-4 border-b border-orange-200/60">
            <div class="flex items-center gap-3">
                <span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-orange-600 text-white shadow-md">
                    <i class="fas fa-truck text-base" aria-hidden="true"></i>
                </span>
                <div>
                    <h3 class="text-base font-bold text-gray-900 flex items-center gap-2">
                        <span>Dispatch Details</span>
                        <span id="cdmBadgeStatus" class="hidden rounded-full px-2 py-0.5 text-[11px] font-semibold bg-blue-100 text-blue-800"></span>
                    </h3>
                    <p class="text-xs text-gray-600 mt-0.5">
                        Invoice #<span id="cdmInvoiceNum" class="font-semibold text-gray-800">-</span>
                        <span id="cdmOrderNumWrap" class="hidden"> | Order #<span id="cdmOrderNum" class="font-semibold text-gray-800">-</span></span>
                    </p>
                </div>
            </div>
            <button type="button" onclick="closeCommonDispatchModal()" class="rounded-lg p-1.5 text-gray-400 hover:bg-gray-200/60 hover:text-gray-700 transition" aria-label="Close modal">
                <i class="fas fa-times text-lg" aria-hidden="true"></i>
            </button>
        </div>

        <!-- Box Selection Tabs (for multi-box dispatches) -->
        <div id="cdmBoxesTabsWrap" class="hidden bg-gray-50/80 px-6 py-2.5 border-b border-gray-200/80 flex items-center justify-between gap-3 overflow-x-auto">
            <div class="flex items-center gap-1.5 min-w-0" id="cdmBoxesPills">
                <!-- Pills generated by JS -->
            </div>
            <button type="button" id="cdmAddNewBoxBtn" onclick="cdmPrepareAddNewBox()" class="shrink-0 inline-flex items-center gap-1 rounded-lg border border-orange-300 bg-white px-2.5 py-1 text-xs font-semibold text-orange-700 hover:bg-orange-50 transition shadow-sm">
                <i class="fas fa-plus text-[10px]" aria-hidden="true"></i>
                Add Box
            </button>
        </div>

        <!-- Loading Spinner -->
        <div id="cdmLoadingSpinner" class="p-10 text-center text-gray-500">
            <i class="fas fa-spinner fa-spin text-2xl text-orange-600 mb-2" aria-hidden="true"></i>
            <p class="text-sm font-medium">Loading dispatch details…</p>
        </div>

        <!-- Alert / Error Banner -->
        <div id="cdmAlertBanner" class="hidden mx-6 mt-4 p-3 rounded-lg border text-xs font-medium"></div>

        <!-- Form Body -->
        <form id="commonDispatchForm" autocomplete="off" class="hidden p-6 space-y-4">
            <input type="hidden" name="invoice_id" id="cdmInputInvoiceId" value="0">
            <input type="hidden" name="dispatch_id" id="cdmInputDispatchId" value="0">
            <input type="hidden" name="order_number" id="cdmInputOrderNumber" value="">
            <input type="hidden" name="exotic_shipment_id" id="cdmInputExoticShipmentId" value="">

            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <!-- Courier Name -->
                <div>
                    <label for="cdmInputCourierName" class="block text-xs font-semibold text-gray-700 mb-1">Courier Name <span class="text-red-500">*</span></label>
                    <select name="courier_name" id="cdmInputCourierName" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-xs text-gray-900 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none" required>
                        <option value="">Select Courier</option>
                        <option value="Shiprocket">Shiprocket</option>
                        <option value="BlueDart">BlueDart</option>
                        <option value="Delhivery">Delhivery</option>
                        <option value="Aramex">Aramex</option>
                        <option value="DHL">DHL Express</option>
                        <option value="FedEx">FedEx</option>
                        <option value="UPS">UPS</option>
                        <option value="DTDC">DTDC</option>
                        <option value="India Post">India Post</option>
                        <option value="Trackon">Trackon</option>
                        <option value="Professional Couriers">Professional Couriers</option>
                    </select>
                </div>

                <!-- AWB / Tracking Code -->
                <div>
                    <label for="cdmInputAwbCode" class="block text-xs font-semibold text-gray-700 mb-1">AWB / Waybill Code <span class="text-red-500">*</span></label>
                    <input type="text" name="awb_code" id="cdmInputAwbCode" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-xs text-gray-900 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none" placeholder="e.g. 143256789" required>
                </div>

                <!-- Tracking URL -->
                <div class="sm:col-span-2">
                    <div class="flex items-center justify-between mb-1">
                        <label for="cdmInputTrackingUrl" class="block text-xs font-semibold text-gray-700">Tracking URL</label>
                        <a id="cdmTestTrackingUrl" href="#" target="_blank" rel="noopener noreferrer" class="hidden text-xs text-blue-600 hover:underline font-medium">
                            <i class="fas fa-external-link-alt text-[10px] mr-1"></i>Test tracking link
                        </a>
                    </div>
                    <input type="url" name="tracking_url" id="cdmInputTrackingUrl" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-xs text-gray-900 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none" placeholder="https://track.courier.com/...">
                </div>

                <!-- Label URL -->
                <div class="sm:col-span-2">
                    <div class="flex items-center justify-between mb-1">
                        <label for="cdmInputLabelUrl" class="block text-xs font-semibold text-gray-700">Label URL</label>
                        <a id="cdmTestLabelUrl" href="#" target="_blank" rel="noopener noreferrer" class="hidden text-xs text-blue-600 hover:underline font-medium">
                            <i class="fas fa-file-pdf text-[10px] mr-1"></i>View shipping label
                        </a>
                    </div>
                    <input type="url" name="label_url" id="cdmInputLabelUrl" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-xs text-gray-900 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none" placeholder="https://labels.courier.com/...">
                </div>

                <!-- Pickup Location -->
                <div>
                    <label for="cdmInputPickupLocation" class="block text-xs font-semibold text-gray-700 mb-1">Pickup Location</label>
                    <select name="pickup_location" id="cdmInputPickupLocation" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-xs text-gray-900 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none">
                        <option value="">Select Pickup Location</option>
                        <?php foreach ($exoticAddresses as $address): ?>
                            <?php 
                            $addrTitle = htmlspecialchars($address['address_title'] ?? '', ENT_QUOTES, 'UTF-8'); 
                            $isDefault = !empty($address['is_default']);
                            ?>
                            <option value="<?= $addrTitle ?>" <?= $isDefault ? 'data-is-default="1"' : '' ?>><?= $addrTitle ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <!-- Dispatch Date -->
                <div>
                    <label for="cdmInputDispatchDate" class="block text-xs font-semibold text-gray-700 mb-1">Dispatch Date <span class="text-red-500">*</span></label>
                    <input type="datetime-local" name="dispatch_date" id="cdmInputDispatchDate" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-xs text-gray-900 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none" required>
                </div>

                <!-- Shipment Status -->
                <div>
                    <label for="cdmInputShipmentStatus" class="block text-xs font-semibold text-gray-700 mb-1">Shipment Status</label>
                    <select name="shipment_status" id="cdmInputShipmentStatus" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-xs text-gray-900 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none">
                        <option value="Ready to Ship">Ready to Ship</option>
                        <option value="Dispatched">Dispatched</option>
                        <option value="IN TRANSIT">IN TRANSIT</option>
                        <option value="OUT FOR DELIVERY">OUT FOR DELIVERY</option>
                        <option value="DELIVERED">DELIVERED</option>
                        <option value="cancellation requested">Cancellation Requested</option>
                        <option value="cancelled">Cancelled</option>
                    </select>
                </div>

                <!-- Box No -->
                <div>
                    <label for="cdmInputBoxNo" class="block text-xs font-semibold text-gray-700 mb-1">Box No.</label>
                    <input type="text" name="box_no" id="cdmInputBoxNo" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-xs text-gray-900 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none" placeholder="1" value="1">
                </div>

                <!-- Box Size -->
                <div>
                    <label for="cdmInputBoxSize" class="block text-xs font-semibold text-gray-700 mb-1">Box Size</label>
                    <select name="box_size" id="cdmInputBoxSize" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-xs text-gray-900 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none">
                        <option value="">Select Size</option>
                        <option value="R-1" data-length="22" data-width="17" data-height="5">R-1 (22x17x5 inch)</option>
                        <option value="R-2" data-length="16" data-width="13" data-height="13">R-2 (16x13x13 inch)</option>
                        <option value="R-3" data-length="16" data-width="11" data-height="7">R-3 (16x11x7 inch)</option>
                        <option value="R-4" data-length="13" data-width="10" data-height="7">R-4 (13x10x7 inch)</option>
                        <option value="R-5" data-length="21" data-width="11" data-height="7">R-5 (21x11x7 inch)</option>
                        <option value="R-6" data-length="11" data-width="10" data-height="8">R-6 (11x10x8 inch)</option>
                        <option value="R-7" data-length="8" data-width="6" data-height="5">R-7 (8x6x5 inch)</option>
                        <option value="R-8" data-length="12" data-width="12" data-height="1.5">R-8 (12x12x1.5 inch)</option>
                        <option value="R-9" data-length="17" data-width="12" data-height="2">R-9 (17x12x2 inch)</option>
                        <option value="R-10" data-length="12" data-width="9" data-height="2">R-10 (12x9x2 inch)</option>
                        <option value="R-11" data-length="10" data-width="10" data-height="2">R-11 (10x10x2 inch)</option>
                        <option value="R-12" data-length="13" data-width="9" data-height="5">R-12 (13x9x5 inch)</option>
                        <option value="R-13" data-length="11" data-width="8" data-height="5">R-13 (11x8x5 inch)</option>
                        <option value="R-14" data-length="14" data-width="12" data-height="10">R-14 (14x12x10 inch)</option>
                        <option value="CUSTOM">Custom Size</option>
                    </select>
                </div>

                <!-- Custom Dimensions (shown when Box Size is CUSTOM) -->
                <div id="cdmCustomDimensionsWrap" class="hidden sm:col-span-2 bg-orange-50/60 p-3 rounded-xl border border-orange-200">
                    <p class="text-xs font-semibold text-orange-900 mb-2">Custom Dimensions (Inches)</p>
                    <div class="grid grid-cols-3 gap-3">
                        <div>
                            <label for="cdmInputLength" class="block text-[11px] font-medium text-gray-700 mb-1">Length</label>
                            <input type="number" step="0.1" min="0" name="length" id="cdmInputLength" class="w-full rounded-lg border border-gray-300 px-2.5 py-1.5 text-xs text-gray-900 bg-white focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none" placeholder="22">
                        </div>
                        <div>
                            <label for="cdmInputWidth" class="block text-[11px] font-medium text-gray-700 mb-1">Width</label>
                            <input type="number" step="0.1" min="0" name="width" id="cdmInputWidth" class="w-full rounded-lg border border-gray-300 px-2.5 py-1.5 text-xs text-gray-900 bg-white focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none" placeholder="17">
                        </div>
                        <div>
                            <label for="cdmInputHeight" class="block text-[11px] font-medium text-gray-700 mb-1">Height</label>
                            <input type="number" step="0.1" min="0" name="height" id="cdmInputHeight" class="w-full rounded-lg border border-gray-300 px-2.5 py-1.5 text-xs text-gray-900 bg-white focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none" placeholder="5">
                        </div>
                    </div>
                </div>

                <!-- Weight (Kg) -->
                <div>
                    <label for="cdmInputWeight" class="block text-xs font-semibold text-gray-700 mb-1">Weight (Kg)</label>
                    <input type="number" step="0.001" min="0" name="weight" id="cdmInputWeight" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-xs text-gray-900 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none" placeholder="0.000">
                </div>

                <!-- Shipping Charges -->
                <div>
                    <label for="cdmInputShippingCharges" class="block text-xs font-semibold text-gray-700 mb-1">Shipping Charges (₹)</label>
                    <input type="number" step="0.01" min="0" name="shipping_charges" id="cdmInputShippingCharges" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-xs text-gray-900 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none" placeholder="0.00">
                </div>

                <!-- Batch No -->
                <div>
                    <label for="cdmInputBatchNo" class="block text-xs font-semibold text-gray-700 mb-1">Batch No.</label>
                    <input type="text" name="batch_no" id="cdmInputBatchNo" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-xs text-gray-900 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none" placeholder="e.g. BATCH-01">
                </div>
            </div>

            <!-- Footer Actions -->
            <div class="flex items-center justify-end gap-3 pt-4 border-t border-gray-100">
                <button type="button" onclick="closeCommonDispatchModal()" class="rounded-lg border border-gray-300 bg-white px-4 py-2 text-xs font-semibold text-gray-700 hover:bg-gray-50 transition">
                    Cancel
                </button>
                <button type="submit" id="cdmSaveBtn" class="inline-flex items-center gap-2 rounded-lg bg-orange-600 px-5 py-2 text-xs font-semibold text-white shadow-sm hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:ring-offset-1 transition">
                    <i class="fas fa-save text-xs" aria-hidden="true"></i>
                    <span>Save Dispatch Details</span>
                </button>
            </div>
        </form>
    </div>
</div>

<script src="<?= htmlspecialchars(base_url('assets/js/pos_message_modal.js'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(base_url('assets/js/dispatch_details_modal.js'), ENT_QUOTES, 'UTF-8') ?>"></script>
