CREATE TABLE IF NOT EXISTS account_group (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    account_group_name VARCHAR(255) NOT NULL,
    item_group VARCHAR(120) NULL DEFAULT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_account_group_name (account_group_name),
    INDEX idx_account_group_active (is_active),
    INDEX idx_account_group_item_group (item_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO account_group (account_group_name, is_active) VALUES
('ART WARE OF IRON', 1),
('ARTICLE OF GLASS', 1),
('BAGS/HAND BAGS', 1),
('BASKET WARE', 1),
('BED SPREAD/COVER/SHEET', 1),
('BOOKS', 1),
('BRASS STATUES', 1),
('BRONZE STATUES', 1),
('Carpets/Handloom dari', 1),
('CUSHION COVER', 1),
('Cut And Semi-polished Stones', 1),
('DVD/CD', 1),
('FABRIC', 1),
('FIBRE DECOR', 1),
('FOOTWEAR', 1),
('GOLD JEWELLERY', 1),
('HAND BAGS', 1),
('HERBAL MEDICINES/COSMETICS ITEMS', 1),
('Imitation Jewelry', 1),
('JACKET/PHIRAN/PONCHU', 1),
('KAFTAN', 1),
('KURTA PYJAMA / ACHKAN', 1),
('LADIES TOPS', 1),
('LEHENGA CHOLI', 1),
('MARBEL & STONE SCULPTURE', 1),
('MENS DHOTIS', 1),
('MIRROR', 1),
('MUSICAL INSTRUMENTS', 1),
('NON SURGICAL MASK', 1),
('PAINTINGS', 1),
('POLYRESIN STATUES', 1),
('QUILTS', 1),
('SALWAR SUITS', 1),
('SAREES', 1),
('SCARF/HANDKERCHIEF', 1),
('SILVER JEWELLERY', 1),
('SKIRTS', 1),
('STOLES AND SHAWLS', 1),
('TABLE MAT', 1),
('TROUSERS', 1),
('T-SHIRTS', 1),
('WOOD FURNITURE', 1),
('WOOD GOD DEITIES', 1),
('WOOD SCULPTURE', 1),
('WRAPS/PRAYER SHAWLS', 1);
