CREATE TABLE IF NOT EXISTS courier_shipments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    invoice_id INT UNSIGNED NULL,
    box_no INT UNSIGNED NULL,
    order_number VARCHAR(80) NULL,
    legacy_dispatch_id INT UNSIGNED NULL COMMENT 'vp_dispatch_details.id when linked',
    partner_code VARCHAR(50) NOT NULL,
    partner_account_id INT UNSIGNED NULL,
    partner_shipment_id VARCHAR(120) NULL,
    awb VARCHAR(80) NULL,
    tracking_url TEXT NULL,
    product_group VARCHAR(20) NULL,
    product_type VARCHAR(20) NULL,
    service_level VARCHAR(80) NULL,
    payment_mode VARCHAR(20) NULL DEFAULT 'prepaid',
    cod_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    is_international TINYINT(1) NOT NULL DEFAULT 0,
    currency VARCHAR(3) NULL,
    charges_total DECIMAL(12,2) NULL,
    label_url TEXT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'draft',
    status_text VARCHAR(255) NULL,
    metadata_json TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_partner (partner_code),
    INDEX idx_awb (awb),
    INDEX idx_order (order_number),
    INDEX idx_invoice_box (invoice_id, box_no),
    INDEX idx_legacy_dispatch (legacy_dispatch_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS courier_api_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partner_code VARCHAR(50) NOT NULL,
    partner_account_id INT UNSIGNED NULL,
    action VARCHAR(80) NOT NULL,
    reference_key VARCHAR(120) NULL,
    request_json MEDIUMTEXT NULL,
    response_json MEDIUMTEXT NULL,
    http_code INT NULL,
    success TINYINT(1) NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_partner_action (partner_code, action),
    INDEX idx_reference (reference_key),
    INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
